// Generated by https://quicktype.io

export interface TestResults {
    hasAllTestRunsPass: boolean;
    testRuns:           TestRun[];
}

export interface TestRun {
    testName:         string;
    hasPassed:        boolean;
    failedTestCases:  FailedTestCase[];
    exceptionMessage: null;
}

export interface FailedTestCase {
    state:         string;
    driverAge:     number;
    relationship:  string;
    studentStatus: string;
    violations:    any[];
    driverGPA:     number;
    maritalStatus: string;
    resultMessage: string;
}



